-- =============================================================================
-- LEADFLOW — 001_Create_roles.sql
-- Increment : 1 — Authentication & User Management
-- Contains  : Extensions, ENUM types, helper functions, roles table + RLS
-- SRS Ref   : UC001, UC002, UC003 — Section 2.1 User Roles
-- SDS Ref   : Section 5.4 — Role class | Section 5.5 — Entity: Role
-- Run Order : 1st — must run before ALL other migrations
-- =============================================================================

-- ---------------------------------------------------------------------------
-- EXTENSIONS
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";   -- uuid_generate_v4()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";    -- crypt(), gen_salt() — password hashing
CREATE EXTENSION IF NOT EXISTS "pg_trgm";     -- GIN index for interaction message search

-- ---------------------------------------------------------------------------
-- ENUM TYPES — single source of truth for all status lifecycles
-- ---------------------------------------------------------------------------

-- User roles aligned to SRS Section 2.1
CREATE TYPE user_role_enum AS ENUM (
    'admin',
    'business_owner',
    'marketing_staff'
);

-- OTP verification states (UC002 — OTP login)
CREATE TYPE otp_status_enum AS ENUM (
    'pending',
    'verified',
    'expired'
);

-- AI content idea lifecycle (UC006 — Validate AI Content Ideas)
CREATE TYPE content_idea_status_enum AS ENUM (
    'pending_validation',   -- generated by GPT-4o, awaiting review
    'approved',             -- validated → auto-creates draft calendar entry
    'rejected'              -- dismissed, never enters content calendar
);

-- Full content scheduling lifecycle (UC007, UC008, UC009)
CREATE TYPE content_status_enum AS ENUM (
    'draft',                -- auto-created on idea approval
    'scheduled',            -- staff set publish date/time
    'uploaded',             -- media attached, ready for auto-publish
    'published',            -- successfully pushed to TikTok
    'failed',               -- auto-publish attempt failed
    'cancelled'             -- removed from queue manually
);

-- Media asset types (UC008 — Upload Content Feed in Calendar)
CREATE TYPE content_type_enum AS ENUM (
    'poster_photo',         -- static image post
    'short_video'           -- TikTok short-form video (max 50 MB)
);

-- TikTok interaction channel (UC010, UC012)
CREATE TYPE channel_type_enum AS ENUM (
    'comment',
    'dm'
);

-- Interaction handling lifecycle (UC011, UC012)
CREATE TYPE interaction_status_enum AS ENUM (
    'unclassified',
    'classified',
    'responded',
    'archived'
);

-- Python FastAPI AI intent categories (SDS Section 9b)
CREATE TYPE sentiment_type_enum AS ENUM (
    'lead_to_sales',        -- HIGH — purchase intent
    'complaint',            -- HIGH — negative experience
    'question',             -- MEDIUM — informational query
    'praise',               -- LOW — positive feedback
    'spam'                  -- LOW — irrelevant / bot
);

-- Priority levels from AI classifier
CREATE TYPE priority_level_enum AS ENUM (
    'high',
    'medium',
    'low'
);

-- Reply send status (UC012)
CREATE TYPE send_status_enum AS ENUM (
    'pending',
    'sent',
    'failed'
);

-- TikTok publish attempt result (UC009)
CREATE TYPE publish_result_enum AS ENUM (
    'success',
    'failed',
    'retrying'
);

-- TikTok OAuth connection state
CREATE TYPE tiktok_connection_status_enum AS ENUM (
    'connected',
    'disconnected',
    'token_expired'
);

-- ---------------------------------------------------------------------------
-- HELPER FUNCTIONS — used across all subsequent migrations
-- ---------------------------------------------------------------------------

-- UTC → WIB (Asia/Jakarta, GMT+7)
-- RULE: all timestamps stored UTC; converted to WIB ONLY in views and frontend
CREATE OR REPLACE FUNCTION to_wib(ts TIMESTAMPTZ)
RETURNS TIMESTAMPTZ LANGUAGE SQL IMMUTABLE AS $$
    SELECT ts AT TIME ZONE 'Asia/Jakarta';
$$;

-- Current WIB timestamp (used for seed data and display assertions)
CREATE OR REPLACE FUNCTION now_wib()
RETURNS TIMESTAMPTZ LANGUAGE SQL STABLE AS $$
    SELECT NOW() AT TIME ZONE 'Asia/Jakarta';
$$;

-- Shared trigger: auto-update updated_at column (reused in 002–010)
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- RLS helper: extract caller's role from Supabase JWT claims
CREATE OR REPLACE FUNCTION get_caller_role()
RETURNS TEXT LANGUAGE SQL STABLE AS $$
    SELECT COALESCE(
        current_setting('request.jwt.claims', TRUE)::jsonb ->> 'role',
        'anonymous'
    );
$$;

-- RLS helper: extract caller's user UUID from Supabase JWT sub claim
CREATE OR REPLACE FUNCTION get_caller_user_id()
RETURNS UUID LANGUAGE SQL STABLE AS $$
    SELECT COALESCE(
        (current_setting('request.jwt.claims', TRUE)::jsonb ->> 'sub')::UUID,
        NULL
    );
$$;

-- ---------------------------------------------------------------------------
-- TABLE: roles
-- SDS Entity: Role — Attributes: roleid, roleName
-- Three fixed roles per SRS Section 2.1. Never deleted.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    id          UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        user_role_enum  NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  roles      IS 'RBAC role definitions. Three fixed roles: admin, business_owner, marketing_staff.';
COMMENT ON COLUMN roles.name IS 'user_role_enum — enforced via FK in users table.';

-- ---------------------------------------------------------------------------
-- RLS: roles
-- ---------------------------------------------------------------------------
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY rls_roles_read_auth ON roles
    FOR SELECT USING (get_caller_role() != 'anonymous');

CREATE POLICY rls_roles_admin_all ON roles
    FOR ALL USING (get_caller_role() = 'admin');