-- =============================================================================
-- LEADFLOW — 011_create_classify_type_messages.sql
-- Increment : 5 — AI Classifier & Interaction Management
-- Contains  : interaction_classifications table (ClassifyTypeMessage) +
--             classification trigger + RLS
-- SRS Ref   : UC011 Classify Interaction Message
-- SDS Ref   : Section 5.4 — ClassifyInteractionMessage class
--             Section 5.5 — Entity: ClassifyTypeMessage — Data Dict
--             Section 5.8 — SD014 Classify Interaction Message
-- STD Ref   : TC011_01, TC011_02
-- Depends   : 001–010 migrations
-- AI Service: Python FastAPI (isolated microservice)
--             Input: message_text → Output: sentiment_type + priority_level
--             Confidence threshold: < 0.60 flagged for manual review
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: interaction_classifications
-- AI classification results from Python FastAPI service.
-- One row per classification attempt (append pattern — preserves history).
-- v_interaction_inbox (010) uses DISTINCT ON to get the latest per message.
-- SDS Entity: ClassifyTypeMessage
-- Attributes: classifyTypeId, sentimentTypeName, priorityLevel
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS interaction_classifications (
    id                  UUID                PRIMARY KEY DEFAULT uuid_generate_v4(),
    interaction_id      UUID                NOT NULL REFERENCES interaction_messages(id) ON DELETE CASCADE,

    -- AI classification output (Python FastAPI service)
    sentiment_type      sentiment_type_enum NOT NULL,   -- lead_to_sales|complaint|question|praise|spam
    priority_level      priority_level_enum NOT NULL,   -- high|medium|low
    confidence_score    NUMERIC(4,3),                   -- 0.000–1.000 from AI model
    ai_reasoning        TEXT,                           -- brief explanation from AI (optional)

    -- Source of classification
    classified_by_ai    BOOLEAN             NOT NULL DEFAULT TRUE,
    classified_by_user  UUID                REFERENCES users(id) ON DELETE SET NULL,  -- manual override

    -- AI suggested reply (UC012 AF1 — Sales Interaction Handling)
    suggested_reply     TEXT,               -- generated by Python service for high-priority messages

    classified_at       TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  interaction_classifications               IS 'AI intent classification results. Python FastAPI service writes here. Append-only per message.';
COMMENT ON COLUMN interaction_classifications.sentiment_type    IS 'lead_to_sales = HIGH → surfaced at inbox top. spam = LOW → bottom.';
COMMENT ON COLUMN interaction_classifications.confidence_score  IS '0.000–1.000. Below 0.600 flagged for manual review in UI.';
COMMENT ON COLUMN interaction_classifications.suggested_reply   IS 'AI-generated reply suggestion. Shown in inbox for lead_to_sales and complaint intents.';
COMMENT ON COLUMN interaction_classifications.classified_by_ai  IS 'TRUE = Python FastAPI. FALSE = manual override by Marketing Staff.';

CREATE INDEX idx_ic_interaction   ON interaction_classifications (interaction_id);
CREATE INDEX idx_ic_sentiment     ON interaction_classifications (sentiment_type);
CREATE INDEX idx_ic_priority      ON interaction_classifications (priority_level);
CREATE INDEX idx_ic_classified_at ON interaction_classifications (classified_at DESC);

-- ---------------------------------------------------------------------------
-- TRIGGER: update interaction_messages.classification_status → 'classified'
-- SDS UC011 NF7: "system updates the interaction record with its type"
-- SRS US011 NF6: "system stores the classification result"
-- Fires after Python FastAPI service inserts classification result.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trigger_classification_update_message_status()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    UPDATE interaction_messages
    SET    classification_status = 'classified',
           updated_at = NOW()
    WHERE  id = NEW.interaction_id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_classification_update_message
    AFTER INSERT ON interaction_classifications
    FOR EACH ROW EXECUTE FUNCTION trigger_classification_update_message_status();

-- ---------------------------------------------------------------------------
-- RLS: interaction_classifications
-- Marketing Staff: SELECT (read AI results) + INSERT for manual override only
-- Admin: full access
-- Business Owner: no access (classification is operational data)
-- ---------------------------------------------------------------------------
ALTER TABLE interaction_classifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY rls_ic_admin_all ON interaction_classifications
    FOR ALL USING (get_caller_role() = 'admin');

CREATE POLICY rls_ic_staff_read ON interaction_classifications
    FOR SELECT USING (get_caller_role() = 'marketing_staff');

CREATE POLICY rls_ic_staff_override ON interaction_classifications
    FOR INSERT WITH CHECK (
        get_caller_role() = 'marketing_staff'
        AND classified_by_ai = FALSE    -- frontend may only insert manual overrides
    );

-- ---------------------------------------------------------------------------
-- VIEW: v_interaction_inbox
-- Created HERE (in 011) because it needs BOTH:
--   interaction_messages (created in 010)
--   interaction_classifications (created in 011)
-- Unified inbox for Marketing Staff — sorted by AI priority (UC012 NF4).
-- Priority: lead_to_sales(1) > complaint(2) > question(3) > praise(4) > spam(5)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_interaction_inbox AS
WITH latest_classification AS (
    SELECT DISTINCT ON (interaction_id)
        interaction_id,
        sentiment_type,
        priority_level,
        confidence_score,
        suggested_reply,
        classified_at
    FROM interaction_classifications
    ORDER BY interaction_id, classified_at DESC
)
SELECT
    im.id                                               AS interaction_id,
    im.tiktok_account_id,
    im.tiktok_message_id,
    im.tiktok_user_handle,
    im.tiktok_post_id,
    im.channel_type,
    im.message_text,
    im.classification_status,
    im.response_status,
    im.response_text,
    im.amount_message_sent,
    to_wib(im.response_sent_at)                         AS responded_at_wib,
    to_wib(im.message_created_at)                       AS message_created_wib,
    to_wib(im.fetched_at)                               AS fetched_at_wib,
    lc.sentiment_type,
    lc.priority_level,
    lc.confidence_score,
    lc.suggested_reply,
    CASE lc.sentiment_type
        WHEN 'lead_to_sales' THEN 1
        WHEN 'complaint'     THEN 2
        WHEN 'question'      THEN 3
        WHEN 'praise'        THEN 4
        WHEN 'spam'          THEN 5
        ELSE 99
    END                                                 AS priority_sort_order,
    up.full_name                                        AS responded_by_name
FROM interaction_messages    im
LEFT JOIN latest_classification lc ON lc.interaction_id = im.id
LEFT JOIN user_profiles         up ON up.user_id = im.responded_by;

COMMENT ON VIEW v_interaction_inbox IS 'Marketing Staff unified inbox. Sorted by priority_sort_order ASC. WIB times.';